### ISSUE TITLE
SMORE'D crashing with too many threads

### ISSUE THREAD

**Issue by annagaines** [appliedbinf/URDO-SMOREd#17]

**Comment by ar0ch** [comment]
I'm inclined to mark this as closed/wont-fix.  I haven't found a reliable way trap this condition (different systems raise different errors).  The optional enhancement is to retry processing samples that don't appear in the results dict after read_processor completes


Thoughts @lavanyarishishwar ?

**Comment by ar0ch** [comment]
SMORED now raises a generic exception when VSEARCH dies prematurely or doesn't process an output see [new lines 110-129](https://github.com/appliedbinf/URDO-SMOREd/commit/11692e4fb1f967f104b7771f2b9472c1ac50113e#diff-a28b10cbc01e06c88c4f901928d55fb9R110-R129)

**Comment by ar0ch** [comment]
New tests need to be written to cover some of this new code however
