### ISSUE TITLE
Test installer at CDC

### ISSUE THREAD

**Issue by ar0ch** [appliedbinf/URDO-SMOREd#18]
The new installer needs to be tested at cdc

@annagaines

**Comment by annagaines** [comment]
Got to the prompt that asks where to install SMORE'D hit enter to choose the default directory and got the below issue. Still testing.

![issueWithSmoredCDCInstall](https://user-images.githubusercontent.com/38079252/73482236-57b0fd00-436b-11ea-8193-52469eb6ad60.png)

**Comment by ar0ch** [comment]
So the version of `dd` on scicomp is from 2010, we need a version from at least 2012.  Reach out to Shatavia and see if we can get scicomp to update `coreutils`.

Will also look at whether the pre-flight script can be used to satisfy this dependency

**Comment by ar0ch** [comment]
I've implemented a _slightly_ customized installer that should now work on scicomp (and anywhere with a `dd` from this century).  

I've tested the new installer at CDC, and the initial install appears to be working correctly.  @annagaines, I'd appreciate if you could run some datasets on scicomp through smored (the command should be aliased already as `smored` in your shell)
